### ISSUE TITLE
Some messages are not configurable

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#1]
So far I've found:
- "You have left the party _list_of_players_"
- "You have joined the party _list_of_players_"
- The output that follows "Below are your current settings:"

**Comment by fallerOfFalls** [comment]
I've just realised that third point isn't explicitly stated in the spec. The spec literally says "configurable introductory statement", though all text that players view is supposed to be configurable. I did say "All error messages should be configurable." though. Anyway, this third point is going to end up being an enhancement anyway because it's tied in with #6.

**Comment by harpereaves** [comment]
I just found (or rather didn't find) another one. private message format is not configurable.

**Comment by fallerOfFalls** [comment]
Also the message you get from the command /yellow list
and the message you get from the command /autismchat reload

**Comment by fallerOfFalls** [comment]
/yellow list will be fixed by the proposed fix for #13

**Comment by harpereaves** [comment]
Found 2 more:
>"That player is red and you cannot join their party."
>"You are yellow and there are players in that party who are not on your yellow list."

These two should refer specifically to that player (and the name of the player(s) should be correctly colour formatted) as per the spec:
>“You cannot join *player* in a party because they are red.”
>“You cannot join the party (*list_of_autismchat_formatted_names...*) because you are yellow and one or more players in that party does not have your permission to be in a party with you.”

**Comment by fallerOfFalls** [comment]
Also the reasons for `{reason}` in `leaveParty`.

**Comment by fallerOfFalls** [comment]
also the output from /autismchat

**Comment by fallerOfFalls** [comment]
Some of these are configurable now, others not. The remaining ones (that I can't find in messages.yml are:
- 'You have left the party {MEMBERS}{REASON}&6.'
- reasons for the above such as 'because {PLAYER} is nolonger in your yellow list' and 'because you switched to red'.
- 'You have joined the party {MEMBERS}.'
- the output from /autismchat

**Comment by fallerOfFalls** [comment]
as well as

``` yaml
notOnYellowList: 'because {Player} is no longer on their yellow list'
```

we need

``` yaml
notOnYourYellowList: 'because {Player} is no longer on your yellow list'
```

Everything else (that I've noticed/reported) seems to be there now. Good work!

**Comment by fallerOfFalls** [comment]
Just found another one.

`````` markdown
reasons:
    because they have joined another party...```
``````
