### ISSUE TITLE
"Invalid statistic" error when people first log in?

### ISSUE THREAD

**Issue by Cassolotl** [RichardsProjects/AutismChat3#19]
I'm not 100% sure this is an AutismChat error, but I don't _think_ it's anything else, so I'll post it here. Mark it invalid if I'm wrong!

The first time people log in (after the switch to Spigot 1.8.4 and AutismChat 3), the console shows pages and pages and pages of this "invalid statistic" thing:

![screen shot 2015-05-16 at 08 37 19](https://cloud.githubusercontent.com/assets/6607512/7665250/0f511b28-fba7-11e4-8d2d-d45c921b60bc.png)

The second time they log in, it's fine!

**Comment by fallerOfFalls** [comment]
If you want to find out whether it's an AutismChat error, try temporarily removing AutismChat (just the .jar file) restart the sever and see if you can reproduce this error.

**Comment by Cassolotl** [comment]
That requires someone who's not logged in post-update to log in at a convenient time - but if I find anyone willing to do that I'll take that opportunity to test it.

**Comment by fallerOfFalls** [comment]
This is a [known vanilla 1.8 issue](https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-51870) - nothing to do with AutismChat.

**Comment by Cassolotl** [comment]
Ohhh blimey, I stand corrected! Thank you. :)
