### ISSUE TITLE
Status colours are not configurable

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#2]
This wouldn't be a problem except that green is currently set to &A GREEN (a sensory nightmare for some autistic people) instead of &2 DARK_GREEN

**Comment by RichardB122** [comment]
So would it be acceptable to simply  simply change the color everywhere to dark green?

**Comment by fallerOfFalls** [comment]
I'd really prefer if it was configurable (in config.yml). Some Autistic people really like the bright colours and I don't want to restrict other server owners to my colour choices. It's also nice to be able to experiment sometimes.

The colour for /blue also needs to be configurable but I neglected to put that in the spec since it's a new colour.

**Comment by fallerOfFalls** [comment]
Fix confirmed.

messages.yml now includes:

``` yaml
# Status Color Codes
yellow: '&6'  
blue: '&1'
green: '&2' 
red: '&4'
```

You have to reload everything in order for changes to take effect.

Strictly speaking, it should be in config.yml not messages.yml since they aren't messages, but all the colour codes are in messages.yml, so I can sort of see why you put it there.
