### ISSUE TITLE
partyJoinErrorMessage 5 should take precidence over 2 and 4

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#20]
when yellow and attempting to join a player you are already in a party with, it says you can't join the party because there are players in it who are yellow and you're not on their yellow list. Which is technically true because I'm not on my own yellow list.
partyJoinErrorMessages `5: '{PLAYER}&r is already in your party.'` should take precidence over
`2: 'There are players in {MEMBERS}&r who are yellow and you are not on their yellow list.'` and
`4: 'You are yellow and there are players in {MEMBERS}&r who are not on your yellow list.'`

This is the same issue as the pre-GitHub-tracking issue number 10 (which was "still apparently happening, sometimes. But haven't figured out how to reproduce."):

> when yellow and attempting to join yourself, it says you can't join the party because there are players in it who are yellow and i'm not on their yellow list. Which is technically true because I'm not on my own yellow list. The check for "are you trying to join yourseelf" should occur before the yellow list check.

This was a slightly misleading bug report, and as a result you fixed it (wrongly) by adding another partyJoinErrorMessage `6: 'The player you entered is you.'`
I have been wondering why that was there, since it's not in the spec. Now I know.

So, we can remove 6, since any cases where you're trying to join yourself will be caught by the check for 5.

**Comment by RichardB122** [comment]
This issue appears to have been fixed in build 36, because I added some code that always counted in your own yellow list. If you attempt to do this now the plugin tells you "You cannot join <player> because you are already in a party with them."

**Comment by fallerOfFalls** [comment]
ha! great job :D
