### ISSUE TITLE
no check for non-yellowlisted players when yellow and joining a group with multiple members

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#37]
When yellow and attempting to join a group that only contains one player, if that player isn't on your yellow list, then you fail to join, and get

```
partyJoinErrorMessages:
    4: 'You cannot join the party {MEMBERS}&c because you are yellow and one or more players in that party does not have your permission to be in a party with you.'
```

however, if the party you're attempting to join contains two players, you succed, regardless of whether it contains players who aren't on your yellow list, and regardless of which player you target!

Haven't been able to test whether this issue is still in the latest build (Build 29). The server I play on has an earlier version.

**Comment by fallerOfFalls** [comment]
I can confirm now that this issue still exists in build 33

**Comment by RichardB122** [comment]
This should hopefully be fixed, but I didn't have access to 3 accounts that I would need to test it.

**Comment by fallerOfFalls** [comment]
yup, seems to be fixed now. thank you.
