### ISSUE TITLE
Cannot change the colour of player message text

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#4]
```
partyChatFormat: "&6[&3Party&6] %name%: &7%message%"
```

Does not result in player messages being light grey. Should it?

**Comment by RichardB122** [comment]
It should be fixed in build 0003 available below:
https://github.com/RichardsProjects/AutismChat3/releases/tag/build_0003

Once you verify it has been fixed I will close the issue.

**Comment by fallerOfFalls** [comment]
Fix confirmed! Thanks!

**Comment by fallerOfFalls** [comment]
This issue isn't fixed for globalChatFormat.
