### ISSUE TITLE
the issues is the name 

### ISSUE THREAD

**Issue by UnnamedDave** [RichardsProjects/AutismChat3#49]
i ask that the name is changed as it is rude

**Comment by fallerOfFalls** [comment]
What is rude about it? For a plugin designed by an autistic person, around autism-specific needs, using the word 'autism' seems quite appropriate.

**Comment by Cassolotl** [comment]
I'm curious to know what a better name might be, @tonyaf123 !

**Comment by fallerOfFalls** [comment]
@tonyaf123 thank you for your feedback anyway. I realised the description on bukkit and curse didn't mention autism, and so it seems weird that it's called AutismChat (like it's just teasing autistic people!). Now updated the description to explain the connection to autism :)
