### ISSUE TITLE
Works with Spigot 1.13

### ISSUE THREAD

**Issue by Cassolotl** [RichardsProjects/AutismChat3#59]
I just wanted to say that this plugin works with Spigot 1.13 as far as I can tell from my testing, because your plugin description [here](https://github.com/RichardsProjects/AutismChat3) says:

> AutismChat is a Free/Libre Open Source Bukkit/Spigot 1.8 (works with 1.9; haven't tested with 1.10 yet) plugin

**Comment by fallerOfFalls** [comment]
Thanks, updated.
