### ISSUE TITLE
"Player has joined the game [and is in your party]."

### ISSUE THREAD

**Issue by Cassolotl** [RichardsProjects/AutismChat3#7]
Hello!

You know those yellow "so-and-so has joined the game" messages when someone logs onto the server?

I think it would be cool if that message also told you if they were in your party.

So if they're not, it'd just say "Player has joined the game".
But if they _are_ in your party, it would say "Player has joined the game and they're in your party". Or something.

harpereaves will probably be happy if the messages are configurable!

(PS: great work, Richard. _thumbs up_)

**Comment by fallerOfFalls** [comment]
This enhancement is supposed to replace the vanilla "Player has joined the game." message. Currently it's in addition to it. And for some reason formatting isn't working, so you see the "&e" at the beginning but the message is white, not yellow.

**Comment by fallerOfFalls** [comment]
Also, it should use "joinMessage" not "joinMessageParty" when the player is you. I know that technically you are in your own party, but it looks weird.

**Comment by fallerOfFalls** [comment]
issues with this feature are now separate: #22, #23, #24
