### ISSUE TITLE
achievement announcements should only be displayed to party members

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#8]
Just like with death messages.

**Comment by RichardB122** [comment]
It doesn't look like this can be done, I'll look into it more thoroughly over the week. But it appears there isn't an event that handles this and that I can use to change the message. Keep this issue open and I will post if I get any more information.

**Comment by fallerOfFalls** [comment]
OK, thanks. This isn't a critical issue as server owners can always just turn off achievement annoucements.

**Comment by RichardB122** [comment]
Yeah it looks like achievement announcements are a vanilla thing and not alterable through the Bukkit/Spigot API so it doesn't appear possible. See this Spigot topic: 

http://www.spigotmc.org/threads/modifying-the-message-that-shows-when-someone-gets-an-achievement.66991/#post-738495
