### ISSUE TITLE
MOTD is too long

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#9]
How hard (expensive) would it be to (optionally in config) give new players a (configurable) book? That way they would have access to info about AutismChat 3 whenever they want without being spammed every time they log in.

**Comment by fallerOfFalls** [comment]
The only known user of AutismChat has categorically stated that they'd never enable this option, so I'm inclined to abandon this feature unless/until another server admin requests it.

**Comment by fallerOfFalls** [comment]
This is still bugging me. And there's a possible solution that doesn't involve books:
a new command: /autismchat motd on|off

There might be a better way though. Perhaps we should be using a proper MOTD plugin instead of trying to build one into AutismChat. But I quite like that it explains stuff specific to AutismChat, and it all works out-of-the-box.

not sure how "/autismchat motd on|off" would play with `firstJoin` though. Maybe `firstJoin` would be rendered obsolete and I've never used it anyway, so we could just remove it.

Welcoming further thoughts, suggestions.

**Comment by RichardB122** [comment]
I'd be fine with firstJoin being removed it was quite complicated to implement and I still never found a way to implement the default yellow list without having to rewrite much of the existing code. I feel it would be a good idea to offer the motd functionality out of the box as long as we provide a way to globally disable it, because some servers might have a more custom motd solution and we don't want that to cause them to not be able to use the plugin.

**Comment by fallerOfFalls** [comment]
OK, so we can drop firstJoin and default yellow list (which I only included in the spec for the sake of completeness) and add "/autismchat motd on|off" command.
templateForFirstLogin in config would then look something like:

``` yaml
templateForFirstLogin:
  partyID: 0
  color: WHITE
  globalChat: true
  displayMotd: true
```

Then motd can be globally disabled (although only for new players, unless AutismChat data is reset) by setting displayMotd to false.
Thoughts?

**Comment by RichardB122** [comment]
Currently working on implementing this and I am wondering how this should work with firstJoin. I was thinking I would just remove it for now since this could be used to achieve the same functionality anyway.

**Comment by fallerOfFalls** [comment]
Yes, removing firstJoin was intended. May not have been clear though.
>OK, so we can drop firstJoin and default yellow list...
